name: Makefile CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python 3.9
      with:
        python-version: "3.9"

    - name: Install dependencies
      run: make install_dependencies

    - name: Check formatting
      run: make check_formatting
